const vitaminData = [
    {
        id: 0,
        fdc_id: 2344711,
        name: 'Apple (Táo)',
        meta: 'A raw apple is 86% water and 14% carbohydrates, with negligible content of fat and protein (table). A reference serving of a raw apple with skin weighing 100 grams provides 52 calories and a moderate content of dietary fiber. Otherwise, there is low content of micronutrients, with the Daily Values of all falling below 10%.',
        a: 3,
        b6: 0.041,
        b12: 0,
        c: 4.6,
        e: 0.18,
        k: 2.2,
    },
    {
        id: 1,
        fdc_id: 2344720,
        name: 'Banana (Chuối)',
        meta: 'A banana is an elongated, edible fruit - botanically a berry produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called "plantains", distinguishing them from dessert bananas. The fruit is variable in size, color, and firmness, but is usually elongated and curved, with soft flesh rich in starch covered with a rind, which may be green, yellow, red, purple, or brown when ripe.',
        a: 3,
        b6: 0.367,
        b12: 0,
        c: 8.7,
        e: 0.1,
        k: 0.5,
    },
    {
        id: 2,
        fdc_id: 2344723,
        name: 'Carambula (Khế)',
        meta: 'The entire fruit is edible, including the slightly waxy skin. The flesh is crunchy, firm, and extremely juicy. It does not contain fibers and has a texture similar in consistency to that of grapes. Carambolas are best consumed shortly after they ripen, when they are yellow with a light shade of green or just after all traces of green have disappeared. They will also have brown ridges at the edges and feel firm. Fruits picked while still slightly green will turn yellow in storage at room temperature, but will not increase in sugar content.',
        a: 66,
        b6: 0.017,
        b12: 0,
        c: 34.4,
        e: 0.15,
        k: 0,
    },
    {
        id: 3,
        fdc_id: 2345303,
        name: 'Sweet Corn (Ngô Ngọt)',
        meta: 'Sweet corn is picked when still in the immature (milk stage) and prepared and eaten as a vegetable, rather than field corn, which is harvested when the kernels are dry and mature (dent stage). Since the process of maturation involves converting sugar to starch, sweet corn stores poorly and must be eaten fresh, canned, or frozen, before the kernels become tough and starchy.',
        a: 9,
        b6: 0.055,
        b12: 0,
        c: 6.8,
        e: 0.07,
        k: 0.3,
    },
    {
        id: 4,
        fdc_id: 2344735,
        name: 'Lychee (Vải)',
        meta: 'Raw lychee fruit is 82% water, 17% carbohydrates, 1% protein, and contains negligible fat (table). In a 100 gram (3.5 oz) reference amount, raw lychee fruit supplies 66 calories of food energy. The raw pulp is rich in vitamin C, having 72 mg per 100 grams - an amount representing 86% of the Daily Value - but contains no other micronutrients in significant content.',
        a: 0,
        b6: 0,
        b12: 0,
        c: 72,
        e: 0,
        k: 0,
    },
    {
        id: 5,
        fdc_id: 169090,
        name: 'Mangosteen (Măng Cụt)',
        meta: 'The fruit of the mangosteen is sweet and tangy, juicy, somewhat fibrous, with fluid-filled vesicles (like the flesh of citrus fruits), with an inedible, deep reddish-purple colored rind (exocarp) when ripe. In each fruit, the fragrant edible flesh that surrounds each seed is botanically endocarp, i.e., the inner layer of the ovary. The seeds are of similar size and shape to almonds.',
        a: 0,
        b6: 0.018,
        b12: 0,
        c: 2.9,
        e: 0,
        k: 0,
    },
    {
        id: 6,
        fdc_id: 2344665,
        name: 'Orange (Cam)',
        meta: 'Orange flesh is 87% water, 12% carbohydrates, 1% protein, and contains negligible fat. As a 100 gram reference amount, orange flesh provides 47 calories, and is a rich source of vitamin C, providing 64% of the Daily Value. No other micronutrients are present in significant amounts',
        a: 34,
        b6: 0.078,
        b12: 0,
        c: 26.7,
        e: 0.2,
        k: 0,
    },
    {
        id: 7,
        name: 'Pepper (Ớt Chuông)',
        meta: 'A raw red bell pepper is 94% water, 5% carbohydrates, 1% protein, and contains negligible fat. A 100 gram (3.5 oz) reference amount supplies 26 calories, and is a rich source of vitamin C - containing 158% of the Daily Value (DV) - vitamin A (20%), and vitamin B6 (23% DV), with moderate contents of riboflavin (12%), folate (12% DV), and vitamin E (11% DV). A red bell pepper supplies twice the vitamin C and eight times the vitamin A content of a green bell pepper.',
        a: 157,
        b6: 0.291,
        b12: 0,
        c: 128,
        e: 1.58,
        k: 4.9,
    },
    {
        id: 8,
        name: 'Pineapple (Dứa)',
        meta: 'Raw pineapple pulp is 86% water, 13% carbohydrates, 0.5% protein, and contains negligible fat. In a 100-gram reference amount, raw pineapple supplies 209 kilojoules (50 kilocalories) of food energy, and is a rich source of manganese (44% Daily Value, DV) and vitamin C (58% DV), but otherwise contains no micronutrients in significant amounts.',
        a: 3,
        b6: 0.112,
        b12: 0,
        c: 47.8,
        e: 0.02,
        k: 0.7,
    },
    {
        id: 9,
        name: 'Pitahaya (Thanh Long)',
        meta: 'As the nutrient content of raw pitaya has not been thoroughly analyzed or published as of 2019, the USDA FoodData Central database reports one limited product label entry from a manufacturer of a branded product, showing that a 100-gram (3+1⁄2-ounce) reference serving of dried pitaya provides 1,100 kilojoules (264 kilocalories) of food energy, 82% carbohydrates, 4% protein, and 11% of the Daily Value each for vitamin C and calcium',
        a: 'N/A',
        b6: 'N/A',
        b12: 0,
        c: 25,
        e: 'N/A',
        k: 'N/A',
    },
];

export default vitaminData;